version: '3'

services:
  distro:
    image: alpine:latest    # Changed the base image to use the Alpine Linux image
    container_name: alpine_distro   # Changed container_name to follow lowercase convention
    restart: always
    entrypoint: tail -f /dev/null
    networks:
      - mynetwork

  database:
    image: postgres:alpine    # Changed the base image to use the Alpine Linux image
    container_name: postgres_db
    volumes:
      - data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    image: nginx:alpine    # Changed the base image to use the Alpine Linux image
    container_name: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80    # Corrected the environment variable name to match NGINX_PORT
    networks:
      - mynetwork
    depends_on:    # Replaced links with depends_on for service orchestration
      - database
      - distro

networks:
  mynetwork:
    driver: bridge

volumes:
  data:
    external: false    # Changed external to false to create the volume internally
